# Generated by Django 5.0.4 on 2024-04-12 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.ImageField(upload_to='company_logos/')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_type', models.CharField(choices=[('Onsite', 'Onsite'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid'), ('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Internship', 'Internship')], max_length=50)),
                ('salary_range', models.CharField(max_length=100)),
                ('application_deadline', models.DateField()),
                ('responsibility', models.TextField()),
                ('qualifications', models.TextField()),
                ('company_details', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Marketing', 'Marketing'), ('Customer Service', 'Customer Service'), ('Human Resource', 'Human Resource'), ('Project Management', 'Project Management'), ('Software Development', 'Software Development'), ('Sales & Communication', 'Sales & Communication'), ('Teaching & Education', 'Teaching & Education'), ('Design & Creative', 'Design & Creative')], max_length=50)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
