# Generated by Django 5.0.4 on 2024-04-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_logo',
            field=models.FileField(upload_to='company_logos/'),
        ),
    ]
