# Generated by Django 5.0.4 on 2024-04-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_logo',
            field=models.ImageField(upload_to='company_logos/'),
        ),
    ]
