# Generated by Django 5.0.4 on 2024-04-14 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_jobapplication_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
