# Generated by Django 5.0.4 on 2024-04-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_jobapplication_applied_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
