# Generated by Django 5.0.4 on 2024-04-09 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseeker',
            old_name='bio',
            new_name='occupation',
        ),
    ]
