# Generated by Django 5.0.4 on 2024-04-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_bio_jobseeker_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
