# Generated by Django 5.0.4 on 2024-04-11 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_employer_company_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='contact_email',
        ),
    ]
