# Generated by Django 5.0.4 on 2024-04-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_employer_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='occupation',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
